title:       "Operating Systems 2021-1 (OS211)"
version:     "0024c---18-Feb-2021"
copyright:   "2021-2021"
description: >- 
  Describe1.
  Describe2.
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Cicak Bin Kadal"
address:          "Pamulang"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://cbkadal.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/cbkadal/os211/"
urlghpage:        "https://cbkadal.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

